### ISSUE TITLE
Can't delete edge with patch function

### ISSUE THREAD

**Issue by LukGer** [xixixao/convex-ents#23]
I have the following schema in my application

```ts
const schema = defineEntSchema({
  users: defineEnt({
    email: v.string(),
  })
    .edges("groups"),
  groups: defineEnt({
    name: v.string(),
  })
    .edges("users"),
});
```

and a mutation for "leaving a group" which looks like this

```ts
export const leaveGroup = mutation({
  args: {
    userId: v.id("users"),
    groupId: v.id("groups"),
  },
  handler: async (ctx, args) => {
    const group = await ctx.table("groups").getX(args.groupId);

    await group.patch({
      users: {
        remove: [args.userId],
      },
    });
  },
});
```

but when executing this mutation, the edge for the specific user is never removed. e.g. when logging the edges of the group before and after the call to patch, the list stays the same.
Do you know why that could be?
Thanks

**Comment by xixixao** [comment]
Hey @LukGer, are you on the latest versions of Ents? I think this bug was fixed here: https://github.com/xixixao/convex-ents/commit/c4e6fbc8e1ecafc30a949c4923b8596ab4a35962

**Comment by LukGer** [comment]
Hi @xixixao,
thanks for pointing that out. I updated form 0.4.2 to 0.4.4 and that fixed the issue.
Thanks a lot
