### ISSUE TITLE
Type 'TableName' does not satisfy the constraint 

### ISSUE THREAD

**Issue by AyoCodess** [xixixao/convex-ents#27]
Hey, following the convex-ents documentation, i ran into a type issue with when importing the types.ts, am i doing something wrong?, At this point im just copying and pasting boiler plate for set up, theres nothing usual abut my setup.

my schema

```js
import { defineEnt, defineEntSchema, getEntDefinitions } from 'convex-ents';
import { v } from 'convex/values';

const schema = defineEntSchema({
  emailList: defineEnt({
    email: v.string(),
    type: v.string(),
    message: v.optional(v.string())
  })
    .index('byEmail', ['email'])
    .index('byType', ['type']),

  messages: defineEnt({
    author: v.string(),
    body: v.string()
  }),

  users: defineEnt({
    email: v.string(),
    name: v.optional(v.string()),
    tokenIdentifier: v.string(),
    isDeleted: v.boolean(),
    updatedAt: v.optional(v.string()),
    updateCount: v.optional(v.number())
  })
    .index('byEmail', ['email'])
    .index('byToken', ['tokenIdentifier'])
});

export const entDefinitions = getEntDefinitions(schema);
````

![Screenshot 2024-06-15 at 09 09 58](https://github.com/xixixao/convex-ents/assets/72066389/3aa1b2e6-9b64-483b-877e-36aa8d9d47c4)
![Screenshot 2024-06-15 at 09 10 13](https://github.com/xixixao/convex-ents/assets/72066389/ba6aac33-339d-4f85-ad3a-531818fb63db)

**Comment by AyoCodess** [comment]
fixed

**Comment by lbybrilee** [comment]
How did you fix this? I'm running into the same problem. i'm sure I made a small error when setting up everything as this is the only issue that references this error but I can't seem to figure it out.
