### ISSUE TITLE
Feedback for “Reading Ents from the Database”

### ISSUE THREAD

**Issue by matthewLuo** [xixixao/convex-ents#32]
What is the purpose of making toggles for the "This is equivalent to the built-in:"? It is hurting my ability to quickly read this doc and also use the CMD+F finder.

**Comment by xixixao** [comment]
Previous feedback was that it was hard to tell which code was vanilla vs Ents when it was all shown directly. I also played with somehow graying out the vanilla snippets, but didn't find a nice visual treatment, so I opted for the current one.

**Comment by chuckwilliams37** [comment]
I have to say, I found the expandable "This is equivalent" openers helpful.
