### ISSUE TITLE
Feedback for “Ent Schema”: Need field option example for many-to-many edges

### ISSUE THREAD

**Issue by cathedral-on-the-moon** [xixixao/convex-ents#35]
Regarding this documentation, 
https://labs.convex.dev/convex-ents/schema#manymany-edges
"This table will have two ID fields, one for each end of the edge. Their names will be inferred from the table names of the connected ents. You can specify them explicitly using the field option."

I need an example of this. It's not clear where to place the field option. Is the the below code correct (assuming that the fields are named tagIdentifier and messageIdentifier, not tagId and messageId)? 

```ts
defineEntSchema({
  messages: defineEnt({
    name: v.string(),
  }).edges("assignedTags", { to: "tags", table: "messages_to_assignedTags", field: "tagIdentifier" }),
  tags: defineEnt({
    text: v.string(),
  }).edges("taggedMessages", {
    name: "messages",
    table: "messages_to_assignedTags",
    field: "messageIdentifier",
  }),
});
```

**Comment by xixixao** [comment]
You have it the other way around.
